---
# tasks file APT update
- name: "Update"
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: "Remove dependencies that are no longer required"
  apt:
    autoremove: yes
    autoclean: yes