---

# tasks file to remove kernel modules and restart
- name: "Load kernel modules"
  community.general.modprobe:
    name: "{{ item }}"
    state: absent
    persistent: present
  with_items: "{{ modprobe_modules}}"

- name: "Reload sysctl"
  shell: sysctl -p --system

