---
# tasks file for openssl-ca-create
- name: "Delete OLD certificates and keys"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ openssl_private_directory }}/{{ openssl_ca_certificate_name }}.key"
    - "{{ openssl_certs_directory }}/{{ openssl_ca_certificate_name }}.crt"

- name: "Generate OpenSSL configuration"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ openssl_ca_directory }}/{{ item }}"
    mode: "0600"
  with_items:
    - openssl.conf

- name: "Create private key for CA with password protection and {{ openssl_certificate_long_size }} bits"
  ansible.builtin.command: openssl genrsa -passout file:.passphrase -out {{ openssl_private_directory }}/{{ openssl_ca_certificate_name }}.key {{ openssl_certificate_long_size }}
  args:
    chdir: "{{ openssl_ca_directory }}"

- name: "Change right for {{ openssl_ca_certificate_name }}.key"
  ansible.builtin.file:
    path: "{{ openssl_private_directory }}/{{ openssl_ca_certificate_name }}.key"
    owner: "{{ openssl_admin_user_name }}"
    group: "{{ openssl_admin_user_group }}"
    mode: "0400"

- name: "Create cert for CA with password protection for {{ openssl_certificate_long_days }} days"
  ansible.builtin.command: openssl req -config openssl.conf -passin file:.passphrase -extensions v3_ca -key {{ openssl_private_directory }}/{{ openssl_ca_certificate_name }}.key -new -x509 -days {{ openssl_certificate_long_days }} -batch -out {{ openssl_certs_directory }}/{{ openssl_ca_certificate_name }}.crt 
  args:
    chdir: "{{ openssl_ca_directory }}"

- name: "Change right for {{ openssl_ca_certificate_name }}.crt"
  ansible.builtin.file:
    path: "{{ openssl_certs_directory }}/{{ openssl_ca_certificate_name }}.crt"
    owner: "{{ openssl_admin_user_name }}"
    group: "{{ openssl_admin_user_group }}"
    mode: "0444"

- name: "Verification"
  ansible.builtin.command: openssl x509 -noout -text -in "{{ openssl_certs_directory }}/{{ openssl_ca_certificate_name }}.crt"
  register: command_output

- debug:
    var: command_output.stdout_lines