---
# tasks file for openssl-create-csr
# need to generate key before with certificate-create-key

- name: "Create directory for OpenSSL configuration files"
  ansible.builtin.file:
    path: "{{ openssl_conf_directory }}/{{ item }}"
    state: directory
    owner: "{{ openssl_admin_user_name }}"
    group: "{{ openssl_admin_user_group }}"
    mode: '0700'
  with_items: "{{ openssl_host_list }}"

- name: "Create directory for CSR"
  ansible.builtin.file:
    path: "{{ openssl_csr_directory }}/{{ item }}"
    state: directory
    owner: "{{ openssl_admin_user_name }}"
    group: "{{ openssl_admin_user_group }}"
    mode: '0700'
  with_items: "{{ openssl_host_list }}"

- name: "Generate CSR configuration on CSR directory"
  ansible.builtin.template:
    src: "openssl-client.conf.j2"
    dest: "{{ openssl_conf_directory }}/{{ item }}/openssl.conf"
    owner: "{{ openssl_admin_user_name }}"
    group: "{{ openssl_admin_user_group }}"
    mode: "0600"
  with_items: "{{ openssl_host_list }}"

- name: "Create CSR"
  ansible.builtin.command: openssl req -new -config {{ openssl_conf_directory }}/{{ item }}/openssl.conf -passin file:.passphrase -batch -key {{ openssl_private_directory }}/{{ item }}/{{ openssl_certificate_name }}.key -out {{ openssl_csr_directory }}/{{ item }}/{{ openssl_certificate_name }}.csr
  args:
    chdir: "{{ openssl_ca_directory }}"
  with_items: "{{ openssl_host_list }}"

- name: "Change right for CSR file"
  ansible.builtin.file:
    path: "{{ openssl_csr_directory }}/{{ item }}/{{ openssl_certificate_name }}.csr"
    owner: "{{ openssl_admin_user_name }}"
    group: "{{ openssl_admin_user_group }}"
    mode: "0444"
  with_items: "{{ openssl_host_list }}"