---
# tasks file to create passphrase file
- name: "Generate passphrase file"
  ansible.builtin.template:
    src: ".passfile.j2"
    dest: "{{ openssl_passfile }}"
    owner: "{{ openssl_passfile_owner }}"
    group: "{{ openssl_passfile_group }}"
    mode: "0600"