---
# tasks file to install packages for admin
  - name: "Install packages for admin"
    package:
      name: "{{ apt_admin_packages }}"
      state: "{{ apt_state }}"
      update_cache: "{{ apt_update_cache }}"
...