---
# tasks file to install common packages
  - name: "Install common packages"
    package:
      name: "{{ apt_common_packages }}"
      state: "{{ apt_state }}"
      update_cache: "{{ apt_update_cache }}"
...