---
# tasks file for roles/system/openssl/openssl-pull-certs
- name: "Create directory for certs"
  ansible.builtin.file:
    path: "{{ openssl_local_directory }}/{{ item }}"
    state: directory
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: '0700'
  register: local_dir
  delegate_to: localhost
  with_items: "{{ openssl_hosts }}"

- name: "Fetch CA certs files"
  ansible.builtin.fetch:
    src: "{{ openssl_sub_certs_directory }}/sub-ca.crt"
    dest: "{{ openssl_local_directory }}/{{ item }}/sub-ca.crt"
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: '0400'
    flat: yes
  with_items: "{{ openssl_hosts }}"

- name: "Fetch certs files"
  ansible.builtin.fetch:
    src: "{{ openssl_sub_certs_directory }}/{{ item.0 }}/{{ item.1 }}.crt"
    dest: "{{ openssl_local_directory }}/{{ item.0 }}/{{ item.1 }}.crt"
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: '0444'
    flat: yes
  with_nested:
    - "{{ openssl_hosts }}"
    - "{{ openssl_certificate_names }}"

- name: "Fetch key files"
  ansible.builtin.fetch:
    src: "{{ openssl_sub_private_directory }}/{{ item.0 }}/{{ item.1 }}.key"
    dest: "{{ openssl_local_directory }}/{{ item.0 }}/{{ item.1 }}.key"
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: '0400'
    flat: yes
  with_nested:
    - "{{ openssl_hosts }}"
    - "{{ openssl_certificate_names }}"