---
# tasks file to install common networks packages with Nala
- name: "Nala update"
  ansible.builtin.command: nala update

- name: "Install common network packages with Nala"
  ansible.builtin.command:
    argv: 
    - nala 
    - install 
    - -y
    - net-tools
    - telnet 
    - sshpass
