---
# tasks file for cfssl-server-init
# Create directories and files for certificates and keys

- name: "Remove old versions"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ cfssl_install_directory }}/cfssl"
    - "{{ cfssl_install_directory }}/cfssljson"

- name: "Remove certificates directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ cfssl_root_directory }}"
    - "{{ cfssl_sub_directory }}"
  when : cfssl_server_type == "root"

- name: "Remove certificates directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ cfssl_sub_directory }}"
  when : cfssl_server_type == "sub"

- name: "Download cfssl"
  ansible.builtin.get_url:
    url: "{{ item.url }}" 
    dest: "{{ cfssl_install_directory }}/{{ item.file }}" 
    mode: '0777'
  with_items:
    - { url: "{{ cfssl_download_url }}", file: "cfssl" }
    - { url: "{{ cfssljson_download_url }}", file: "cfssljson" }
    - { url: "{{ cfssl_certinfo_download_url }}", file: "cfssl-certinfo" }

- name: "Create Cert directory for {{ cfssl_root_prefix}}ca"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ cfssl_admin_user_name }}"
    group: "{{ cfssl_admin_user_group }}"
    mode: '0700'
  with_items:
    - "{{ cfssl_root_directory }}"
    - "{{ cfssl_sub_directory }}"
  when : cfssl_server_type == "root"

- name: "Create Cert directory for {{ cfssl_sub_prefix}}ca"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ cfssl_admin_user_name }}"
    group: "{{ cfssl_admin_user_group }}"
    mode: '0700'
  with_items:
    - "{{ cfssl_sub_directory }}"
  when : cfssl_server_type == "sub"

