---
# tasks file to generate private key on dedicated directory
- name: "Create directory for private key"
  ansible.builtin.file:
    path: "{{ openssl_private_directory }}/{{ item }}"
    state: directory
    owner: "{{ openssl_admin_user_name }}"
    group: "{{ openssl_admin_user_group }}"
    mode: '0700'
  with_items: "{{ openssl_host_list }}"

- name: "Generate private key"
  ansible.builtin.command: openssl genrsa -passout file:.passphrase -out {{ openssl_private_directory }}/{{ item }}/{{ openssl_certificate_name }}.key {{ openssl_certificate_short_size }}
  args:
    chdir: "{{ openssl_ca_directory }}"
  with_items: "{{ openssl_host_list }}"

- name: "Change right for key file"
  ansible.builtin.file:
    path: "{{ openssl_private_directory }}/{{ item }}/{{ openssl_certificate_name }}.key"
    owner: "{{ openssl_admin_user_name }}"
    group: "{{ openssl_admin_user_group }}"
    mode: "0400"
  with_items: "{{ openssl_host_list }}"