---
# tasks file to remove all certificates files on admin_hostname

- name: "Remove keys"
  ansible.builtin.file:
    path: "{{ openssl_private_directory }}/{{ item.0 }}/{{ item.1 }}.key"
    state: absent
  with_nested:
    - "{{ openssl_hosts }}"
    - "{{ openssl_certificate_names }}"

- name: "Remove PEM keys"
  ansible.builtin.file:
    path: "{{ openssl_private_directory }}/{{ item.0 }}/{{ item.1 }}.pem"
    state: absent
  with_nested:
    - "{{ openssl_hosts }}"
    - "{{ openssl_certificate_names }}"

- name: "Remove certificate files on {{ admin_hostname }}"
  ansible.builtin.file:
    path: "{{ openssl_certs_directory }}/{{ item.0 }}/{{ item.1 }}.crt"
    state: absent
  with_nested:
    - "{{ openssl_hosts }}"
    - "{{ openssl_certificate_names }}"

- name: "Remove CSR"
  ansible.builtin.file:
    path: "{{ openssl_csr_directory }}/{{ item.0 }}/{{ item.1 }}.csr"
    state: absent
  with_nested:
    - "{{ openssl_hosts }}"
    - "{{ openssl_certificate_names }}"

- name: "Remove openssl configuration file"
  ansible.builtin.file:
    path: "{{ openssl_conf_directory }}/{{ item.0 }}/openssl-{{ item.1 }}.conf"
    state: absent
  with_nested:
    - "{{ openssl_hosts }}"
    - "{{ openssl_certificate_names }}"
