---
# tasks file to remove all certificates files on admin_hostname

- name: "Remove keys {{ openssl_certificate_name }}.key"
  ansible.builtin.file:
    path: "{{ openssl_private_directory }}/{{ item }}/{{ openssl_certificate_name }}.key"
    state: absent
  with_items: "{{ openssl_host_list }}"

- name: "Remove keys {{ openssl_certificate_name }}.key.pem"
  ansible.builtin.file:
    path: "{{ openssl_private_directory }}/{{ item }}/{{ openssl_certificate_name }}.pem"
    state: absent
  with_items: "{{ openssl_host_list }}"

- name: "Remove certificate {{ openssl_certificate_name }}.crt files on {{ admin_hostname }}"
  ansible.builtin.file:
    path: "{{ openssl_certs_directory }}/{{ item }}/{{ openssl_certificate_name }}.crt"
    state: absent
  with_items: "{{ openssl_host_list }}"

- name: "Remove CSR {{ certificate_name }}.csr"
  ansible.builtin.file:
    path: "{{ openssl_csr_directory }}/{{ item }}/{{ openssl_certificate_name }}.csr"
    state: absent
  with_items: "{{ openssl_host_list }}"

- name: "Remove openssl configuration file"
  ansible.builtin.file:
    path: "{{ openssl_conf_directory }}/{{ item }}/openssl.conf"
    state: absent
  with_items: "{{ openssl_host_list }}"