---
# tasks file to remove network packages
- name: "Remove network packages"
  package:
    name: "{{ apt_network_packages }}"
    state: "{{ apt_state }}"
    update_cache: "{{ apt_update_cache }}"
...