---
# tasks file to install common packages with APT
- name: "Install common packages with APT"
  package:
    name: [ 
      "python3-pip", 
      "nfs-common", 
      "tree", 
      "htop" 
    ]
    state: latest
    update_cache: true

- name: "Install common packages for isa-server"
  package:
    name: [ "sipcalc" ]
    state: latest
    update_cache: true
  when: inventory_hostname == "isa-server"
