---
# tasks file to install common network packages with APT
- name: "Install common packages with APT"
  package:
    name: [ 
      "net-tools", 
      "telnet", 
      "sshpass", 
    ]
    state: latest
    update_cache: true