---
- name: "Get certificates serial numbers" 
  ansible.builtin.shell: 
    cmd: "grep {{ item }}  {{ openssl_sub_directory }}/index.txt | cut -f4" 
    chdir: "{{ openssl_sub_directory }}"
  register: serial_number
  with_items: "{{ openssl_hosts }}"

- name: "Remove new certs"
  ansible.builtin.file:
    path: "{{ openssl_sub_newcerts_directory }}/{{ item.stdout }}.pem"
    state: absent
  with_items: "{{ serial_number.results }}"

- name: "Remove certs from index.txt"
  ansible.builtin.lineinfile:
    path: "{{ openssl_sub_directory }}/index.txt"
    regexp: "^(.*){{ item.stdout }}(.*)$"
    state: absent
  with_items: "{{ serial_number.results }}"

- name: "Create directory for certs"
  ansible.builtin.file:
    path: "{{ openssl_sub_certs_directory }}/{{ item }}"
    state: directory
    owner: "{{ openssl_admin_user_name }}"
    group: "{{ openssl_admin_user_group }}"
    mode: '0700'
  with_items: "{{ openssl_hosts }}"

- name: "Generate certificate signed with our own CA certificate" 
  ansible.builtin.command: openssl ca -passin file:{{ openssl_sub_passfile }} -batch -config "{{ openssl_sub_directory }}/openssl.conf" -extfile "{{ openssl_sub_csr_directory }}/{{ item.0 }}/openssl-{{ item.1 }}.conf" -extensions v3_req -days 3650 -notext -in "{{ openssl_sub_csr_directory }}/{{ item.0 }}/{{ item.1 }}.csr" -out "{{ openssl_sub_certs_directory }}/{{ item.0 }}/{{ item.1 }}.crt" 
  args:
    chdir: "{{ openssl_sub_directory }}"
  with_nested:
    - "{{ openssl_hosts }}"
    - "{{ openssl_certificate_names }}"

- name: "Change right for certificates"
  ansible.builtin.file:
    path: "{{ openssl_sub_certs_directory }}/{{ item.0 }}/{{ item.1 }}.crt"
    mode: "0444"
  with_nested:
    - "{{ openssl_hosts }}"
    - "{{ openssl_certificate_names }}"
